name: Flutter build
on:
  push:
    branches:
      - master

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Flutter setup
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.x'
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Build the appbundle
        run: flutter build appbundle
      - name: Upload artifact on github
        uses: actions/upload-artifact@v2
        with:
          name: release-appbundle
          path: build/app/outputs/bundle/release/app-release.aab
